---
title: "Eligibility"
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)


```


Applicants must 

- Be enrolled as an undergraduate student at the time of the institute.
- Be US citizen or permanent resident
- Have knowledge of and interest in statistics, computing, probability, calculus, and linear algebra. These prerequisites are flexible. 
- Have interest in using empirical data to answer scientific questions.

Participants will be required to follow COVID-19 related regulations of the University of California Irvine, including proof of vaccination. 

<!--GPA maybe will add later-->

## Application Form 

Please fill out the following application form: (link [here](https://forms.gle/TRHnUFEswUQkcVqx9)). The application form  will ask you to 

- answer questions about your **background and interest**
- provide an email address of a faculty member who will submit a **recommendation letter** for you
- upload your **unofficial college transcripts**
- upload your **resume/CV**
